### ISSUE TITLE
app size?

### ISSUE THREAD

**Issue by EmilAlipiev** [VincentH-Net/CSharpForMarkup#1]
I wonder if you have any idea or experience regarding how this effects app size. which one is better using c# or xaml or it wont even matter.

**Comment by VincentH-Net** [comment]
Hi @EmilAlipiev, using C# or XAML will not matter for app size.

The differences when using C# are:
- A better development experience
- A smaller cognitive load for the developer, because you only need to work in one language and you don't need to scatter your code in extra patterns to bridg the gap between XAML and C#.

For more on the cognitive load when using XAML, see [Saving Xamarin.Forms](https://xamarinhelp.com/saving-xamarin-forms/)
