### ISSUE TITLE
Curious: how do you rate your approach for other XAML variations like UWP?

### ISSUE THREAD

**Issue by DierkDroth** [VincentH-Net/CSharpForMarkup#2]
>> Imo XAML in Xamarin Forms exists for historical reasons, to convince developers that are familiar with other Microsoft XAML dialects to onboard

Would you make the same statement for UWP? Meaning, would you see any reason your approach would not have similar benefits on UWP?

**Comment by VincentH-Net** [comment]
Yes, I think the same fundamental pro's and con's apply to XAML for UWP. At its core, you are talking about declaring UI in XML versus C# (or any other programming language designed for humans).

One additional consideration is that for UWP there IS a mature visual design tool: **Blend**.

However, as stated by [Nick Randolph](https://nicksnettravels.builttoroam.com/post-2019-03-11-blend-still-lives-aspx/), this may not matter anymore:

> Now with hot reload support in most major frameworks, the reliance on a design time experience as all but gone away. I think it’s time to say RIP to Blend and move forward with a different approach to XAML developers

**Comment by DierkDroth** [comment]
Thanks for your feedback.

>> One additional consideration is that for UWP there IS a mature visual design tool: Blend.
Interestingly enough Blend never was used by our development team. For the most part it was hand coded XAML (in WPF though). Anyway, this stresses your point of "why going with a different language/concept than C# when there's no benefit?" ... and I agree to that.

**Comment by DierkDroth** [comment]
@VincentH-Net sorry I wanted to revisit that topic:

Would you have any interest in extending your great work to WinUI/UWP? I'm sure you're aware that Platform UNO gained significant traction recently which is why we're making significant investments to explore Platform UNO. 

Having your approach as a 'ready-to-use' option definitely would make WinUI/UWP (and Platform UNO) much more appealing.

**Comment by VincentH-Net** [comment]
That is interesting; I would like to get some insight in how many developers would want this.

Do I understand correctly that even though UWP/WinUI has both the best XAML and the best XAML design tool (Blend), having to use them is so unappealing to your team that it would influence whether you would adopt UNO or not?

Also, could you share something about your team? Do they have XAML experience, what (type of) apps do you build...

FYI I am already working on C# Markup for .NET MAUI - because I will use that in my job. I am also considering creating C# Markup for Blazor (so a HTML DSL instead of XAML) - because we create complex web applications at my company.

UNO is very interesting because it targets both web and native apps, and it does not use HTML to do it. I would love to create C# Markup for this but it would depend on how many devs want it and whether UNO will be used at my company

**Comment by DierkDroth** [comment]
@VincentH-Net  thanks for follow up. Unfortunately I only could disclose limited information publicly. However, you could PM me if you wanted dierk <dot> droth <at> ninjatrader <dot> com

**Comment by VincentH-Net** [comment]
@DierkDroth Apps + ecosystem look interesting (from public info).
I will investigate UNO and their thoughts on this, and then PM you.

**Comment by DierkDroth** [comment]
Great. I already had a brief email thread with Jerome (CTO) and Francois (CEO) on that subject.

**Comment by VincentH-Net** [comment]
Quick update - I have most C# Markup fundamentals proven working in UNO, pattern MAI spec++, and got Mihhail to get LiveSharp working for hot reload on UNO (wasm not yet)

More soon.

**Comment by DierkDroth** [comment]
Excellent, sounds like some significant progress has been made. Thanks for the update!

FYI UNO WASM is priority to our project. Hence, would be great if C# Markup would be working there as well.

**Comment by VincentH-Net** [comment]
It does. All heads work with C# Markup so far. Only livesharp not yet on wasm, Mihhail needs to implement signalr for that. He is aware; will share your need with him

**Comment by DierkDroth** [comment]
Thanks again

**Comment by VincentH-Net** [comment]
@DierkDroth after a year-long interrupt due to a changed work role, I finally found the opportunity to create a preview release of C# Markup 2 for WinUI 3 and UNO💯

It is not production ready yet, but I am very interested if you could look at it and see if it would work for you - especially any issues or missing functionality. Thanks!

**Comment by DierkDroth** [comment]
Thanks @VincentH-Net. At this point I'm knees deep in a different project. However, I saw the announcement and will look into as I got back to where CSharpForMarkup could make sense.
